/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "CupSensor_CupSensor.h"
#include "CupSensor_CupSensorUnit.h"
#include "CupSensor_CircularBuffer.h"
#include "photodiodes_aliases.h"
#include "photodiodes.h"
#include "leds_aliases.h"
#include "leds.h"
#include "dacOut_aliases.h"
#include "dacOut.h"
#include "UART.h"
#include "Test_time_pin_aliases.h"
#include "Test_time_pin.h"
#include "RED_pin_aliases.h"
#include "RED_pin.h"
#include "GREEN_pin_aliases.h"
#include "GREEN_pin.h"
#include "BLUE_pin_aliases.h"
#include "BLUE_pin.h"
#include "CupSensor_DMA_ADC_dma.h"
#include "CupSensor_TIA.h"
#include "CupSensor_isr_1.h"
#include "CupSensor_Control_Reg_Led.h"
#include "CupSensor_VDAC8.h"
#include "CupSensor_DMA_Filter_dma.h"
#include "CupSensor_ADC_DelSig.h"
#include "CupSensor_DMA_Filter_to_DAC_dma.h"
#include "CupSensor_Clock_2.h"
#include "UART_IntClock.h"
#include "CupSensor_ADC_DelSig_Ext_CP_Clk.h"
#include "CupSensor_ADC_DelSig_Bypass_P03_aliases.h"
#include "CupSensor_ADC_DelSig_Bypass_P03.h"
#include "CupSensor_ADC_DelSig_IRQ.h"
#include "CupSensor_ADC_DelSig_theACLK.h"
#include "cy_em_eeprom.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

