/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "SDA_1_aliases.h"
#include "SDA_1.h"
#include "SCL_1_aliases.h"
#include "SCL_1.h"
#include "Interrupt_aliases.h"
#include "Interrupt.h"
#include "UART.h"
#include "Clock_1.h"
#include "I2C.h"
#include "I2C_PVT.h"
#include "timer_clock.h"
#include "isr.h"
#include "Timer.h"
#include "isr_1.h"
#include "SPIM_led_control.h"
#include "SPIM_led_control_PVT.h"
#include "Pin_sclk_aliases.h"
#include "Pin_sclk.h"
#include "Pin_miso_aliases.h"
#include "Pin_miso.h"
#include "Pin_latch_aliases.h"
#include "Pin_latch.h"
#include "Pin_mosi_aliases.h"
#include "Pin_mosi.h"
#include "Clock_SPI.h"
#include "Timer_led_updater.h"
#include "isr_update_leds.h"
#include "UART_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

