/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "SDA_1_aliases.h"
#include "SDA_1.h"
#include "SCL_1_aliases.h"
#include "SCL_1.h"
#include "Interrupt_aliases.h"
#include "Interrupt.h"
#include "UART.h"
#include "Clock_1.h"
#include "I2C.h"
#include "I2C_PVT.h"
#include "timer_clock.h"
#include "isr_BLINK_TIMER.h"
#include "Timer.h"
#include "isr_UART.h"
#include "SPIM_led_control.h"
#include "SPIM_led_control_PVT.h"
#include "Pin_sclk_aliases.h"
#include "Pin_sclk.h"
#include "Pin_latch_aliases.h"
#include "Pin_latch.h"
#include "Pin_mosi_aliases.h"
#include "Pin_mosi.h"
#include "Clock_SPI.h"
#include "Timer_led_updater.h"
#include "isr_update_leds.h"
#include "photodiodes_aliases.h"
#include "photodiodes.h"
#include "dacOut_aliases.h"
#include "dacOut.h"
#include "leds_aliases.h"
#include "leds.h"
#include "CupSensor_CupSensor.h"
#include "CupSensor_CupSensorUnit.h"
#include "CupSensor_CircularBuffer.h"
#include "Test_time_pin_aliases.h"
#include "Test_time_pin.h"
#include "test_LED_aliases.h"
#include "test_LED.h"
#include "UART_IntClock.h"
#include "CupSensor_Opamp_1.h"
#include "CupSensor_TIA.h"
#include "CupSensor_isr_DMA.h"
#include "CupSensor_Control_Reg_Led.h"
#include "CupSensor_VDAC8.h"
#include "CupSensor_DMA_ADC_dma.h"
#include "CupSensor_ADC_DelSig.h"
#include "CupSensor_LED_clock.h"
#include "CupSensor_ADC_DelSig_Ext_CP_Clk.h"
#include "CupSensor_ADC_DelSig_Bypass_P32_aliases.h"
#include "CupSensor_ADC_DelSig_Bypass_P32.h"
#include "CupSensor_ADC_DelSig_IRQ.h"
#include "CupSensor_ADC_DelSig_theACLK.h"
#include "cy_em_eeprom.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

